# Generated by Django 5.2.3 on 2025-06-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='Enlace directo a la imagen en internet', max_length=300, null=True, verbose_name='URL de la imagen'),
        ),
    ]
